### ISSUE TITLE
Error: Robinhood responded with code 401

### ISSUE THREAD

**Issue by Gillinghammer** [Ladinn/algotrader#11]
Running into an issue that happened recently, so I am wondering if something changed in the Robinhood API.

```
const instrument = await Instrument.getBySymbol(symbol);
// works fine & returns the instrument from Robinhood
// But now when I use that generated instrument to get the Quote I have a 401 response from Robinhood
const stockQuote = await instrument.getQuote();
// Error: Robinhood responded with code 401
```

**Comment by trapadulli** [comment]
I have the same issue. Robinhood must've updated. So, I downloaded Algotrader thinking it would resolve issue however I'm still having the same issue after npm'ing latest. Also, I don't understand how to use getMFA() decide to use it....

**Comment by Gillinghammer** [comment]
@trapadulli 

So this is kinda hacky but I got things working by editing the file at **node_modules/algotrader/objects/broker/robinhood/Instrument.js**

Edit the request to include an Authorization Header like so.

Now when you call instrument.getQuote() you must pass in your authenticated user like: instrument.getQuote(user).

```
getQuote(user) {
    const _this = this;
    return new Promise((resolve, reject) => {
      request(
        {
          uri: _this.urls.quote,
          headers: {
            Authorization: 'Bearer ' + user.getAuthToken()
          })
....
```


@Ladinn Pretty hacky like I said, but let me know if you'd like me to do a pull request for this.

**Comment by trapadulli** [comment]
thanks! I look forward to trying this tonight.

**Comment by Ladinn** [comment]
@Gillinghammer Thanks for figuring this out!

I just updated the readme, docs, and Instrument class' getQuote and populate methods to reflect the change. After testing without errors this issue is resolved.

**Comment by trapadulli** [comment]
@Ladinn  _preAuth rejects, body: "Unable to log in with provided credentials."...
but my User object has a token. Why?

**Comment by trapadulli** [comment]
> @trapadulli can you post the version you're using, the full error, and the code that causes the error?
+ algotrader@1.4.3
updated 1 package and audited 885 packages in 2.269s
found 0 vulnerabilities


User {
  url: 'https://api.robinhood.com',
  username: 'trapadulli',
  password: '****************',
  token:
   'eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJleHAiOjE1NDc3NDU3NzEsInRva2VuIjoiODBnZUpVbnNpOWFKMmVhRkdDQkJzTXVubVJuZjNOIiwidXNlcl9pZCI6ImYxNDdmODRjLTgxM2UtNGY1My1hZTZlLTg3ZGY5ZDc0ZDdlYyIsIm9wdGlvbnMiOmZhbHNlfQ.CwDlE4D47CVLB6FjfGd5chFTyQQ-PdPfY-PjDSjNyVBF3kc4EY4ep0wlZhjlR96ssYZHdXk5vtpug69ALsQL253WLkiiYWFWhhEi4SHzMByukCrZfuL3BMkZ7BILEb_YnkJF2fFZZGrZSRJZwB9Sg3G-qYb2GtWc3qfNfeb1YjBfwKgtNInn05rnGIj82U8NoScQtCcWUScBl8ugFK5dXNjU18fs7devBZxrcN2Ztz3Jej37e47xKu_mxZDfiVNdbJWDA9z4pcBOOdG93Zq2-IUSy00pjF_Oc9uUx-TGSee878uq8Vqw5kzwYuQsOLRX2Nbd5bzDPf8A6p0l_wJKtQ',
  account: '5UG25589' }
``` (node:67400) UnhandledPromiseRejectionWarning: Error: "Unable to log in with provided credentials." ```

**Comment by trapadulli** [comment]
``` 
const robinhood = require('algotrader').Robinhood;
const User = robinhood.User;
const Instrument = robinhood.Instrument;
const Quote = robinhood.Quote;
const Order = robinhood.Order;
var fs = require('fs');

var logging = require('../Library/logging');
const user = new User(logging.getUser(), logging.getPass()); //hide
//console.log("auth failure---------------------------------")
console.log(user)
var twilioSMS = require('../Library/twilioSMS');


module.exports = {
    getQuote: function(symbol, callback){
      console.log(logging.getPass()); //hide
//console.log("auth failure------------------------------)
      console.log(user)
       var quotePrice = new Promise(function(resolve,reject){ user.authenticate()
        .then(() => {
         Instrument.getBySymbol(symbol).then(async underlyingStock => {
            let stockQuote =  underlyingStock.getQuote();
            resolve(stockQuote.price.last);
        });
     })
    })
        quotePrice.then(function(value) {
           console.log("value :" + value)
        callback(value);
        });
    }, .....
```

**Comment by trapadulli** [comment]
> @trapadulli can you post the version you're using, the full error, and the code that causes the error?

I can't get past authenticate 
```user.authenticate()
    .then(() => {
       console.log("inside authenticate............")
    })
    .catch(error => {
       console.log(error)
    })```
