### ISSUE TITLE
auth

### ISSUE THREAD

**Issue by trapadulli** [Ladinn/algotrader#6]
has auth broken? I haven't looked into it I was just made aware all my trades are failing.

this is the error message:

node:64416) UnhandledPromiseRejectionWarning: Error: <h1>Not Found</h1><p>The requested URL /api-token-auth/ was not found on this server.</p>

thanks

**Comment by trapadulli** [comment]
is this project abandoned?

**Comment by trapadulli** [comment]
fixed it good enough. updated authenticate:

authenticate() {
 			
		const _this = this;
		return new Promise((resolve, reject) => {
			request.post({
				uri: _this.url + "/oauth2/token/",
				
				form: {
					username: _this.username,
					password: _this.password,
					client_id: 'c82SH0WZOsabOXGP2sxqcj34FxkvfnWRZBKlBjFS',
					grant_type: "password",
        			scope: "internal"
				}
			}, (error, response, body) => {
				
				if (error) reject(error);
				else if (response.statusCode !== 200) reject(new LibraryError(body));
				else {
					_this.token = JSON.parse(body).access_token;
					//console.log(_this.url)
					_this.getAccount().then(account => {
						//console.log(account)
						_this.account = account.account_number;
						_this.password = _this.password;
						resolve(_this);
					}).catch(error => reject(error));
				}
				
			})
		})
	}

**Comment by trapadulli** [comment]
...and updated header authenticate in relevant methods:

headers: {
					'Authorization': 'Bearer ' + _this.token
				}

**Comment by udnisap** [comment]
Looks like this api is very much outdated. the getAccounts is also resulting different data format than this expect

**Comment by Ladinn** [comment]
Thanks @trapadulli for providing this! Sorry for the delay in the update, but this has been updated in 1.4.0 and along with a few other features.
